"""Added TipoParo table, updated Parada and RegistroProduccion models

Revision ID: 29e48a56bb4c
Revises: 
Create Date: 2025-04-15 15:50:31.358040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e48a56bb4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_paro_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('inicio', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('fin', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duracion_minutos', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tipos_paros', ['tipo_paro_id'], ['id'])
        batch_op.drop_column('tipo')
        batch_op.drop_column('duracion_min')

    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suma_minutos_alistamiento', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suma_minutos_programado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suma_minutos_calidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suma_minutos_averias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suma_minutos_organizacional', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.drop_column('suma_minutos_organizacional')
        batch_op.drop_column('suma_minutos_averias')
        batch_op.drop_column('suma_minutos_calidad')
        batch_op.drop_column('suma_minutos_programado')
        batch_op.drop_column('suma_minutos_alistamiento')

    with op.batch_alter_table('paradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracion_min', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('duracion_minutos')
        batch_op.drop_column('fin')
        batch_op.drop_column('inicio')
        batch_op.drop_column('tipo_paro_id')

    # ### end Alembic commands ###
