"""cambiar campos de minutos a float para decimales

Revision ID: 4d6ed2414b45
Revises: fca5b9fee271
Create Date: 2025-04-22 08:38:05.994816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6ed2414b45'
down_revision = 'fca5b9fee271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.alter_column('suma_minutos_alistamiento',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_programado',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_calidad',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_averias',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_organizacional',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.alter_column('suma_minutos_organizacional',
               existing_type=sa.Float(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_averias',
               existing_type=sa.Float(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_calidad',
               existing_type=sa.Float(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_programado',
               existing_type=sa.Float(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_alistamiento',
               existing_type=sa.Float(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
