"""remove redundant paro columns

Revision ID: 7014560ab473
Revises: 86ad424a4237
Create Date: 2025-04-21 12:28:16.276195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7014560ab473'
down_revision = '86ad424a4237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.drop_column('suma_paro_alistamiento')
        batch_op.drop_column('suma_paro_calidad')
        batch_op.drop_column('suma_paro_organizacional')
        batch_op.drop_column('suma_paro_programado')
        batch_op.drop_column('suma_paro_averias')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suma_paro_averias', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suma_paro_programado', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suma_paro_organizacional', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suma_paro_calidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suma_paro_alistamiento', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
