"""agregar columna registro_ids_original a tablas paradas

Revision ID: 78b927a89a17
Revises: 4d6ed2414b45
Create Date: 2025-04-22 12:27:11.961912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b927a89a17'
down_revision = '4d6ed2414b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registro_ids_original', sa.String(length=255), nullable=True))

    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.alter_column('suma_minutos_alistamiento',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_programado',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_calidad',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_averias',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_organizacional',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.alter_column('suma_minutos_organizacional',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_averias',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_calidad',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_programado',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('suma_minutos_alistamiento',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('paradas', schema=None) as batch_op:
        batch_op.drop_column('registro_ids_original')

    # ### end Alembic commands ###
