"""add capas field to RegistroProduccion

Revision ID: 86ad424a4237
Revises: e00178a540a0
Create Date: 2025-04-20 21:30:19.992966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ad424a4237'
down_revision = 'e00178a540a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.drop_column('capas')

    # ### end Alembic commands ###
