"""Permitir valores nulos en id_producto de registro_produccion

Revision ID: e00178a540a0
Revises: b05c329009de
Create Date: 2025-04-18 12:05:50.917142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00178a540a0'
down_revision = 'b05c329009de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
