""" cambio de nombres suma_segundos a suma_minutos

Revision ID: fca5b9fee271
Revises: 9374cb3388aa
Create Date: 2025-04-22 07:52:06.471806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca5b9fee271'
down_revision = '9374cb3388aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suma_minutos_alistamiento', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suma_minutos_programado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suma_minutos_calidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suma_minutos_averias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suma_minutos_organizacional', sa.Integer(), nullable=True))
        batch_op.drop_column('suma_segundos_calidad')
        batch_op.drop_column('suma_segundos_alistamiento')
        batch_op.drop_column('suma_segundos_programado')
        batch_op.drop_column('suma_segundos_organizacional')
        batch_op.drop_column('suma_segundos_averias')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suma_segundos_averias', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suma_segundos_organizacional', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suma_segundos_programado', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suma_segundos_alistamiento', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suma_segundos_calidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('suma_minutos_organizacional')
        batch_op.drop_column('suma_minutos_averias')
        batch_op.drop_column('suma_minutos_calidad')
        batch_op.drop_column('suma_minutos_programado')
        batch_op.drop_column('suma_minutos_alistamiento')

    # ### end Alembic commands ###
